### ISSUE TITLE
Docker image in Kubernetes fails to read token file

### ISSUE THREAD

**Issue by awuetz** [aws/amazon-eks-pod-identity-webhook#67]
Hello all,

i'm not sure, if I'm right here to open this issue, but maybe you can give some guidance.

**What happened**:
We are triing to install the cloudwatch-agent in our kubernetes setup which runs on AWS EKS.
Therefor we are following the AWS documentation https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/ContainerInsights.html 
As soon as the pods are starting, they get in the Error state and then into CrashLoopBackOff.

The pod logs tell me the following:
```
2020/08/02 20:51:43 I! 2020/08/02 20:51:40 E! [EC2] getting new session info:  WebIdentityErr: role ARN is not set
2020/08/02 20:51:40 I! attempt to access ECS task metadata to determine whether I'm running in ECS.
2020/08/02 20:51:41 W! retry [0/3], unable to get http response from http://169.254.170.2/v2/metadata, error: unable to get response from http://169.254.170.2/v2/metadata, error: Get "http://169.254.170.2/v2/metadata": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
2020/08/02 20:51:42 W! retry [1/3], unable to get http response from http://169.254.170.2/v2/metadata, error: unable to get response from http://169.254.170.2/v2/metadata, error: Get "http://169.254.170.2/v2/metadata": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
2020/08/02 20:51:43 W! retry [2/3], unable to get http response from http://169.254.170.2/v2/metadata, error: unable to get response from http://169.254.170.2/v2/metadata, error: Get "http://169.254.170.2/v2/metadata": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
2020/08/02 20:51:43 I! access ECS task metadata fail with response unable to get response from http://169.254.170.2/v2/metadata, error: Get "http://169.254.170.2/v2/metadata": context deadline exceeded (Client.Timeout exceeded while awaiting headers), assuming I'm not running in ECS.
I! Detected the instance is OnPrem
2020/08/02 20:51:43 Reading json config file path: /opt/aws/amazon-cloudwatch-agent/bin/default_linux_config.json ...
/opt/aws/amazon-cloudwatch-agent/bin/default_linux_config.json does not exist or cannot read. Skipping it.
2020/08/02 20:51:43 Reading json config file path: /etc/cwagentconfig/..2020_08_02_20_51_36.020038921/cwagentconfig.json ...
2020/08/02 20:51:43 Find symbolic link /etc/cwagentconfig/..data
2020/08/02 20:51:43 Find symbolic link /etc/cwagentconfig/cwagentconfig.json
2020/08/02 20:51:43 Reading json config file path: /etc/cwagentconfig/cwagentconfig.json ...
Valid Json input schema.
Got Home directory: /root
No csm configuration found.
No metric configuration found.
Configuration validation first phase succeeded

2020/08/02 20:51:43 I! Config has been translated into TOML /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.toml
2020/08/02 20:51:44 I! AmazonCloudWatchAgent Version 1.246396.0.
2020-08-02T20:51:44Z I! will use file based credentials provider
2020-08-02T20:51:44Z I! Starting AmazonCloudWatchAgent (version 1.246396.0)
2020-08-02T20:51:44Z I! Loaded outputs: cloudwatchlogs
2020-08-02T20:51:44Z I! Loaded inputs: cadvisor k8sapiserver
2020-08-02T20:51:44Z I! Tags enabled:
2020-08-02T20:51:44Z I! Agent Config: Interval:1m0s, Quiet:false, Hostname:"ip-10-12-132-234.eu-central-1.compute.internal", Flush Interval:1s
2020-08-02T20:51:44Z W! Cannot find in cluster config: failed to read token file "/var/run/secrets/kubernetes.io/serviceaccount/token": open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory
2020-08-02T20:51:44Z E! Failed to build config: stat /.kube/config: no such file or directory
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x98 pc=0x17271ae]

goroutine 1 [running]:
k8s.io/client-go/kubernetes.(*Clientset).CoreV1(...)
        /local/p4clients/pkgbuild-lFOT0/workspace/src/CWAgent/vendor/src/k8s.io/client-go/kubernetes/clientset.go:315
github.com/influxdata/telegraf/plugins/inputs/k8sapiserver.(*K8sAPIServer).Start(0xc0002c4ee0, 0x24dac00, 0xc0002c5ca0, 0x7fda75f04c60, 0xc0002c4ee0)
        /local/p4clients/pkgbuild-lFOT0/workspace/src/CWAgent/src/github.com/influxdata/telegraf/plugins/inputs/k8sapiserver/k8sapiserver.go:107 +0xde
github.com/influxdata/telegraf/agent.(*Agent).Run(0xc00000e0d8, 0xc0000441e0, 0x0, 0x0)
        /local/p4clients/pkgbuild-lFOT0/workspace/src/CWAgent/src/github.com/influxdata/telegraf/agent/agent.go:398 +0x565
main.reloadLoop(0xc000044120, 0x3555f00, 0x0, 0x0, 0x3555f00, 0x0, 0x0, 0xc00061fd70, 0x0, 0x0, ...)
        /local/p4clients/pkgbuild-lFOT0/workspace/src/CWAgent/src/github.com/influxdata/telegraf/cmd/telegraf/telegraf.go:266 +0x87
main.main()
        /local/p4clients/pkgbuild-lFOT0/workspace/src/CWAgent/src/github.com/influxdata/telegraf/cmd/telegraf/telegraf.go:470 +0x56b
```

I'm wondering about this line here: `W! Cannot find in cluster config: failed to read token file "/var/run/secrets/kubernetes.io/serviceaccount/token": open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory`
As per my understanding, the eks-pod-identity-webhook should take care of, that AWS_WEB_IDENTITY_TOKEN_FILE
points to */var/run/secrets/eks.amazonaws.com/serviceaccount/token* instead of */var/run/secrets/kubernetes.io/serviceaccount/token*

So is this an issue with the webhook or with the image of cloudwatch-agent?

**Environment**:
- AWS Region: eu-central-1
- EKS Platform version (if using EKS, run `aws eks describe-cluster --name <name> --query cluster.platformVersion`): "eks.1"
- Kubernetes version (if using EKS, run `aws eks describe-cluster --name <name> --query cluster.version`): "1.17"
- Webhook Version: unknown
- AmazonCloudWatchAgent Version 1.246396.0.

**Comment by micahhausler** [comment]
Can you post the pod or deployment yaml you are using, as well as the service account and any annotations?  The error you're seeing looks like `automountServiceAccountToken: false` is set, which is a separate issue than this project.

**Comment by awuetz** [comment]
Hi @micahhausler 

thanks for the feedback. Today i was gathering your additional configs out of the system. And the first thing i tried was to set `automountServiceAccountToken: True` 
As soon as i did this the cloudwatch-agent pods were running stable. But I'm quite sure that i had tested with the automount option before creating the ticket.. Don't really know what the root cause for this was, though glad for your answer.
